@echo off
echo Starting deployment to production server...

echo Creating deployment archive...
tar -czf deployment.tar.gz out/

echo Uploading files to server...
scp -i "C:\Users\Sean\.ssh\shop_agrikoph" deployment.tar.gz root@143.42.189.57:/tmp/

echo Deploying files on server...
ssh -i "C:\Users\Sean\.ssh\shop_agrikoph" root@143.42.189.57 "cd /tmp && tar -xzf deployment.tar.gz && sudo rm -rf /var/www/shop/* && sudo cp -r out/* /var/www/shop/ && sudo chown -R www-data:www-data /var/www/shop && sudo chmod -R 755 /var/www/shop && rm -f deployment.tar.gz && rm -rf out && echo 'Deployment completed successfully!'"

echo Cleaning up local files...
del deployment.tar.gz

echo ✅ Deployment completed! Site should be live at https://shop.agrikoph.com/