name: Simple Deploy

on:
  workflow_dispatch:  # Manual deployment only

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_WC_API_URL: ${{ secrets.NEXT_PUBLIC_WC_API_URL }}
          WC_CONSUMER_KEY: ${{ secrets.WC_CONSUMER_KEY }}
          WC_CONSUMER_SECRET: ${{ secrets.WC_CONSUMER_SECRET }}
          ADMIN_PASSWORD_HASH: ${{ secrets.ADMIN_PASSWORD_HASH }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Create Deployment Package
        run: |
          # Create deployment directory
          mkdir -p deploy

          # Copy built files
          cp -r .next deploy/
          cp package*.json deploy/

          # Create simple deployment script
          cat > deploy/deploy.sh << 'EOF'
          #!/bin/bash
          set -e

          echo "Starting deployment..."

          # Install production dependencies
          npm ci --omit=dev

          # Create/update systemd service (optional)
          if command -v systemctl &> /dev/null; then
            sudo systemctl reload-or-restart agriko-app 2>/dev/null || true
          fi

          echo "Deployment complete!"
          EOF

          chmod +x deploy/deploy.sh

      - name: Deploy via SSH (if secrets configured)
        if: ${{ secrets.SERVER_HOST != '' }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # Create deployment directory if it doesn't exist
            mkdir -p ~/agriko-deploy
            cd ~/agriko-deploy

            # Pull latest code
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }}.git .
              git checkout main
            fi

            # Run deployment
            chmod +x deploy/deploy.sh
            ./deploy/deploy.sh

      - name: Deployment Status
        run: |
          if [ "${{ secrets.SERVER_HOST }}" = "" ]; then
            echo "⚠️  No server secrets configured - build completed but not deployed"
            echo "To deploy, add these secrets to your GitHub repository:"
            echo "  - SERVER_HOST: your server IP or domain"
            echo "  - SERVER_USER: SSH username"
            echo "  - SSH_PRIVATE_KEY: SSH private key"
            echo "  - NEXT_PUBLIC_WC_API_URL: WooCommerce API URL"
            echo "  - WC_CONSUMER_KEY: WooCommerce consumer key"
            echo "  - WC_CONSUMER_SECRET: WooCommerce consumer secret"
            echo "  - ADMIN_PASSWORD_HASH: Hashed admin password"
            echo "  - JWT_SECRET: JWT secret (32+ chars)"
          else
            echo "✅ Deployment completed successfully"
          fi